[package]
name = "mc-loot-finder"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
pumpkin-world = { git = "https://github.com/Br0bserver/Pumpkin.git", rev = "3acb1c47b74d7438d870924098d8407deaeed97d" }
pumpkin-data = { git = "https://github.com/Br0bserver/Pumpkin.git", rev = "3acb1c47b74d7438d870924098d8407deaeed97d" }
pumpkin-util = { git = "https://github.com/Br0bserver/Pumpkin.git", rev = "3acb1c47b74d7438d870924098d8407deaeed97d" }
serde_json = "1.0"

[[bin]]
name = "mc-loot-finder"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = true
strip = true
