[package]
name = "mc-loot-finder"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
pumpkin-world = { git = "https://github.com/Br0bserver/Pumpkin.git", rev = "0021fb9b354e8dc8ab07b5cfb7ca69af0c2b5374" }
pumpkin-data = { git = "https://github.com/Br0bserver/Pumpkin.git", rev = "0021fb9b354e8dc8ab07b5cfb7ca69af0c2b5374" }
pumpkin-util = { git = "https://github.com/Br0bserver/Pumpkin.git", rev = "0021fb9b354e8dc8ab07b5cfb7ca69af0c2b5374" }
serde_json = "1.0"

[[bin]]
name = "mc-loot-finder"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = true
strip = true
