[package]
name = "mc-loot-finder"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
pumpkin-world = { git = "https://github.com/Br0bserver/Pumpkin.git", rev = "68804c39b6cdc05a1d98f4c7d081a91e46564512" }
pumpkin-data = { git = "https://github.com/Br0bserver/Pumpkin.git", rev = "68804c39b6cdc05a1d98f4c7d081a91e46564512" }
pumpkin-util = { git = "https://github.com/Br0bserver/Pumpkin.git", rev = "68804c39b6cdc05a1d98f4c7d081a91e46564512" }
serde_json = "1.0"

[[bin]]
name = "mc-loot-finder"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = true
strip = true
