use super::{Chest, Kind, Scan, invalid_scan};

pub fn stub_scan(kind: Kind, chunk_x: i32, chunk_z: i32) -> Option<Scan> {
    match kind {
        Kind::BuriedTreasure if chunk_x == 0 && chunk_z == -22 => Some(Scan {
            valid_structure: true,
            chests: vec![Chest {
                structure_chunk_x: chunk_x,
                structure_chunk_z: chunk_z,
                x: 9,
                y: 63,
                z: -343,
                loot_table: "minecraft:chests/buried_treasure".to_owned(),
                ordinal: 0,
                loot_seed: -2156648588641602659,
            }],
        }),
        Kind::Shipwreck if chunk_x == 14 && chunk_z == 8 => Some(Scan {
            valid_structure: true,
            chests: vec![
                Chest {
                    structure_chunk_x: chunk_x,
                    structure_chunk_z: chunk_z,
                    x: 219,
                    y: 60,
                    z: 142,
                    loot_table: "minecraft:chests/shipwreck_treasure".to_owned(),
                    ordinal: 0,
                    loot_seed: 8114931824729312727,
                },
                Chest {
                    structure_chunk_x: chunk_x,
                    structure_chunk_z: chunk_z,
                    x: 235,
                    y: 61,
                    z: 144,
                    loot_table: "minecraft:chests/shipwreck_supply".to_owned(),
                    ordinal: 0,
                    loot_seed: -3774492170699737302,
                },
                Chest {
                    structure_chunk_x: chunk_x,
                    structure_chunk_z: chunk_z,
                    x: 224,
                    y: 61,
                    z: 145,
                    loot_table: "minecraft:chests/shipwreck_map".to_owned(),
                    ordinal: 1,
                    loot_seed: -2986182992758690057,
                },
            ],
        }),
        Kind::EndCity if chunk_x == 86 && chunk_z == 64 => Some(Scan {
            valid_structure: true,
            chests: vec![
                Chest {
                    structure_chunk_x: chunk_x,
                    structure_chunk_z: chunk_z,
                    x: 1390,
                    y: 106,
                    z: 1033,
                    loot_table: "minecraft:chests/end_city_treasure".to_owned(),
                    ordinal: 0,
                    loot_seed: -8159403464680465500,
                },
                Chest {
                    structure_chunk_x: chunk_x,
                    structure_chunk_z: chunk_z,
                    x: 1392,
                    y: 106,
                    z: 1031,
                    loot_table: "minecraft:chests/end_city_treasure".to_owned(),
                    ordinal: 0,
                    loot_seed: 7731847916610423894,
                },
            ],
        }),
        Kind::WoodlandMansion if chunk_x == -221 && chunk_z == -52 => Some(Scan {
            valid_structure: true,
            chests: vec![
                Chest {
                    structure_chunk_x: chunk_x,
                    structure_chunk_z: chunk_z,
                    x: -3534,
                    y: 69,
                    z: -817,
                    loot_table: "minecraft:chests/woodland_mansion".to_owned(),
                    ordinal: 0,
                    loot_seed: 901766045902888527,
                },
                Chest {
                    structure_chunk_x: chunk_x,
                    structure_chunk_z: chunk_z,
                    x: -3507,
                    y: 69,
                    z: -820,
                    loot_table: "minecraft:chests/woodland_mansion".to_owned(),
                    ordinal: 0,
                    loot_seed: -8848498207950452855,
                },
                Chest {
                    structure_chunk_x: chunk_x,
                    structure_chunk_z: chunk_z,
                    x: -3510,
                    y: 91,
                    z: -814,
                    loot_table: "minecraft:chests/woodland_mansion".to_owned(),
                    ordinal: 8,
                    loot_seed: -4018319632420834225,
                },
                Chest {
                    structure_chunk_x: chunk_x,
                    structure_chunk_z: chunk_z,
                    x: -3510,
                    y: 91,
                    z: -802,
                    loot_table: "minecraft:chests/woodland_mansion".to_owned(),
                    ordinal: 9,
                    loot_seed: -6821191583928121953,
                },
                Chest {
                    structure_chunk_x: chunk_x,
                    structure_chunk_z: chunk_z,
                    x: -3510,
                    y: 91,
                    z: -798,
                    loot_table: "minecraft:chests/woodland_mansion".to_owned(),
                    ordinal: 0,
                    loot_seed: -5138943431233530681,
                },
                Chest {
                    structure_chunk_x: chunk_x,
                    structure_chunk_z: chunk_z,
                    x: -3510,
                    y: 91,
                    z: -786,
                    loot_table: "minecraft:chests/woodland_mansion".to_owned(),
                    ordinal: 1,
                    loot_seed: -109245569350193768,
                },
                Chest {
                    structure_chunk_x: chunk_x,
                    structure_chunk_z: chunk_z,
                    x: -3509,
                    y: 66,
                    z: -774,
                    loot_table: "minecraft:chests/woodland_mansion".to_owned(),
                    ordinal: 1,
                    loot_seed: 3860057794113135919,
                },
            ],
        }),
        _ => None,
    }
}
